# Dockerfile.mt-gpro-commun
FROM maven:3.6.3-openjdk-11-slim AS BUILDER
ARG VERSION=3.5.0.0-SNAPSHOT
WORKDIR /build/
COPY . /build/
# socle
COPY socle/pom.xml /build/
RUN mvn clean install
# socle-j2ee
COPY socle-j2ee/pom.xml /build/socle-j2ee/
RUN mvn clean install
# socle-j2ee-tiers
COPY socle-j2ee-tiers/pom.xml /build/socle-j2ee-tiers/
RUN mvn clean install
# scole-j2ee-mt
COPY scole-j2ee-mt/pom.xml /build/scole-j2ee-mt/
RUN mvn clean install
# mt-socle
COPY mt-socle/pom.xml /build/mt-socle/
RUN mvn clean install
# mt-commun
COPY mt-commun/pom.xml /build/mt-commun/
RUN mvn clean install
# mt-gpro-commun
COPY mt-gpro-commun/pom.xml /build/mt-gpro-commun/
RUN mvn clean install

#copie
COPY mt-gpro-commun/mt-gpro-commun-rest/target/mt-gpro-commun-rest-3.5.0.0-SNAPSHOT.war /build/

# Utilisez l'image Tomcat officielle comme base
FROM tomcat:10.1

COPY commun-server.xml /usr/local/tomcat/conf/server.xml

# Copiez le WAR dans le répertoire webapps de Tomcat
WORKDIR /usr/local/tomcat/webapps/

COPY --from=BUILDER /build/mt-gpro-commun-rest-3.5.0.0-SNAPSHOT.war .

# Exposez le port sur lequel Tomcat écoute
EXPOSE 8889
#EXPOSE 8080
# Commande par défaut pour démarrer Tomcat lors de l'exécution du conteneur
CMD ["catalina.sh", "run"]

