version: '3.8'

services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres  # Add the password here
      POSTGRES_DB: commercial-industriel
    ports:
      - "5432:5432"
    volumes:
      - pg:/var/lib/postgresql/data

  mt-gpro-commun:
    image: bensassiahmed/commun
    ports:
      - "8889:8889"

  ma-gpro-logistique:
    image: bensassiahmed/logistique 
    ports:
      - "8890:8890"

  frontend:
    image: bensassiahmed/front
    ports:
      - "8080:8080"

volumes:
  pg:


